In [2]:
#Question: Write a Numpy program to get the Numpy version.
import numpy as np
print(np.__version__)

1.23.3


In [4]:
import numpy as np 
print(np.__version__)
print(np.show_config())

1.23.3
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [7]:
# Write a NumPy program to test whether none of the elements of a given array are zero.
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of array is zero:
False


In [9]:
# Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
print("Original numbers:")
print(a)
print(b)
print("Comparison - greater")
print(np.greater(a, b))
print("Comparison - greater_equal")
print(np.greater_equal(a, b))
print("Comparison - less")
print(np.less(a, b))
print("Comparison - less_equal")
print(np.less_equal(a, b))

Original numbers:
[1 2 3 4 5]
[4 5 6 7 8]
Comparison - greater
[False False False False False]
Comparison - greater_equal
[False False False False False]
Comparison - less
[ True  True  True  True  True]
Comparison - less_equal
[ True  True  True  True  True]


In [11]:
# Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
import numpy as np
a = np.array([1, 7, 13, 105])
print("Size of the memory occupied by the array:")
print("%d bytes" % (a.size * a.itemsize))

Size of the memory occupied by the array:
16 bytes


In [13]:
# Write a NumPy program to create an array of integers from 30 to 70.
import numpy as np
arr = np.arange(30,71)
print("Expected Array: ")
print(arr)

Expected Array: 
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [19]:
# Write a NumPy program to create an array of all even integers from 30 to 70.
import numpy as np
arr = np.arange(30,71,2)
print("Array of all even integers from 30 to 70:")
print(arr)

Array of all even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [29]:
# Write a NumPy program to create a 3x3 identity matrix.
import numpy as np
x = np.matrix('1,2,3;4,5,6;7,8,9')
print("3x3 matrix:")
print(x,end='\n\n')
print("3x3 zeros matrix:")
print(np.zeros((3,3)))


3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3x3 zeros matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
# Write a search NumPy program to create a 3X4 array and iterate over it.
import numpy as np 
arr= np.arange(11,21)
for i in arr:
    print(i, end=", ")

print("\n\n3x4 array:")
arr = np.arange(1,13).reshape(3,4)
print(arr)
print("Iterate over the array:")
for i in arr:
    for j in i:
        print(j, end=", ")

11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 

3x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Iterate over the array:
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 

In [40]:
# Write a search NumPy program to create a 3X4 array and iterate over it.
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
    print(x,end=", ")


'''
It is an efficient multidimensional iterator object using which it is possible to iterate over an array. 
Each element of an array is visited using Python's standard Iterator interface. 
The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering.
'''

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 

"\nIt is an efficient multidimensional iterator object using which it is possible to iterate over an array. \nEach element of an array is visited using Python's standard Iterator interface. \nThe order of iteration is chosen to match the memory layout of an array, without considering a particular ordering.\n"